import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>React Dog Parks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the Dog Parks App!
        </h1>

        <div className={styles.grid}>
          <p>We will add a picture here later</p>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/mariya-lazarova/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Personal Project created by Mariya Lazarova
        </a>
      </footer>
    </div>
  )
}
